### ISSUE TITLE
IE Bugs

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#128]
## hich vaght say nakon sitet too ie6 dorost baz beshe !

``` css
div#box {
   width: 100px;
   border: 2px solid black;
   padding: 10px;
}
```

**Too IE6 arz box 100 mohasebe mishe !!!!**

yani tamame bug haro ham fix konin too in yeki mimooni

pas kal nandaz ke migam projato ro too ie6 tahvil migiram :trollface: kh kh kh kh

[ali.md/iebugs](http://ali.md/iebugs)
