### ISSUE TITLE
C8 W2 S2

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#443]
## Rules
- `display:inline` height ya harchizi mesle padding va margin nabayad dashte bashe
- Madar ertefaye bache hayi ke float daran ro nemigire !
## Some tips

**Box shadow sample**

``` css
.box {
  width: 100px;
  height: 100px;
  background-color: #E67E22;
  margin: 50px;
  box-shadow: 50px 50px 0 -20px red, -50px 50px 0 -20px red,50px -50px -20px red, -50px -50px -20px red;
  -moz-box-shadow: 50px 50px 0 -20px red, -50px 50px 0 -20px red,50px -50px -20px red, -50px -50px -20px red;
  -webkit-box-shadow: 50px 50px 0 -20px red, -50px 50px 0 -20px red,50px -50px -20px red, -50px -50px -20px red;
}
```

**Transition**

``` css
.box {
  -webkit-transition: all 0.5s;
  -moz-transition: all 0.5s;
  -ms-transition: all 0.5s;
  -o-transition: all 0.5s;
  transition: all 0.5s;
}
```
## Class Works

  Basic menu like this : https://gist.github.com/AliMD/5955085
## Students
- Sayed Amin  Akbarzadeh  @akbarzadeamin **(Absent:exclamation:)**
- Sayed Reza  Mahmoodian  @mahmoodian
- S Hossein Behkamal  @hoseinBL
- S Mahdi Qooryani  @qooryani
- AmirReza  Derayati  @albertreza
- Mohammad Hassan Kohansal  @SingularDesigner
- Mohammad  Sedaghat  @sedaghat
- Ehsan Shadmehri @ehsansh
- Mahdi Jannatian @mahdi-jannatian
- Ali Ebrahimi  @lastshepherd
- Mahdi Ghayoor @mghayour
## Home Work

  Menu like this : https://gist.github.com/AliMD/5955088
