### ISSUE TITLE
C12 W1 S8

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#609]
### Topics
- Cascading Style Sheets
- CSS Basic: http://ali.md/css
- ID/Class
### CSS Sample

``` css
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>CSS Sample ;)</title>
  <style type="text/css">
    body {
      background-color: #312;
      color:white;
    }
    h1 {
      font-size: 45px;
      font-family: "monospace";
    }
    p {
      font-size: 18px;
      line-height: 2;
      color: #DDD;
    }
  </style>
</head>
<body>
  <h1>Lorem ipsum dolor sit.</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo illum aperiam provident esse nesciunt tempore fugit officiis itaque quia fuga. Autem blanditiis quo molestias corporis!
  </p>
</body>
</html>
```
### Home Work

ali.md/css ro basic ro kamel bekhoonid va barash tamrinasho anjam bedin
