### ISSUE TITLE
C13 W2 S4

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#630]
## Topics
1. yadavari `:before` `:after` : http://jsbin.com/EkIRocEF/1/edit
2. Position: http://jsbin.com/usAhoyeY/3/edit
3. Submenu: http://jsbin.com/iMiSAjo/3/edit

``` css
* {
  padding: 0;
  margin: 0;
}

body {
  background-color: hsl(40, 15%, 85%);
}

menu.main {
  list-style-type: none;
  margin: 20px 20px 0 10px;
  background-color: hsl(35, 90%, 48%);
}

menu.main:after{
  content: " ";
  display: block;
  width: 0;
  height: 0;
  clear: left;
}

menu.main li {
  border-left: 1px dashed white;
  float: left;
  position: relative;
}

menu.main li:hover{
  background-color: hsl(35, 90%, 45%);
}

menu.main li:first-child{
  border-left: 0 none;
}

menu.main li a {
  text-decoration: none;
  color: white;
  font-size: 20px;
  text-transform: capitalize;
  padding: 7px 10px;
  display: block;
  transition: all 700ms;
}

menu.main li:hover a{
  padding: 7px 20px;
  transition: all 300ms;
}

menu.main menu{
  list-style-type: none;
  position: absolute;
  left: 0;
  top: 100%;
  min-width: 100%;
  background-color: hsl(35, 90%, 48%);
  display: none;
}

menu.main li:hover menu{
  display: block;
}

menu.main li li{
  float: none;
  border-left: none;
  border-top: 1px dashed white;
  white-space: nowrap;
}
```
### Home Work

Creative Sub Menu
### Students Level (Home Work)
1. Hamed Nosrati @hamednosrati [Menu](http://jsbin.com/EluruBeF/5) :+1: 
2. Alireza Haghpanah @alirezahp [Menu](http://jsbin.com/USunuqul/1) :+1: 
3. Mohammad Amin Alizade Golestani  @MAgolestani [Menu](http://jsbin.com/oNUgaMAC/2) :+1: 
4. Alireza Hassanzadeh Baradaran @alirezahb [Menu](http://jsbin.com/aRUFaBip/2) :+1: 
5. Salman Sedighi @sedsalman :facepunch: :x: 
6. Alireza Akhlaghi @akhibing :facepunch: :x: 
7. Javad Pourhosaini @pourhosaini :-1:  :facepunch: :x:
