### ISSUE TITLE
C13 W2 S7

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#640]
### @font-face

``` css
@font-face {
  font-family: 'font_name';
  src: url('font_file_name.eot'); /* old browser like ie6 */
  src: url('font_file_name.eot?#iefix') format('embedded-opentype'),
       url('font_file_name.woff') format('woff'),
       url('font_file_name.ttf') format('truetype'),
       url('font_file_name.svg#tangerineregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

``` css
body{
    font-family: 'local font name', 'font_name' ,arial ,sans;
}
```

Sample : https://github.com/AliMD/1Tuts/blob/WebDesign-Old/%5Bcss3%5D%20Fonts/Custome%20web%20fonts.html
### Google Web Font

GWF : http://www.google.com/fonts/
sample : http://jsbin.com/ucupuq/1/edit
### Persian

[ali.md/1fonts](http://ali.md/1fonts)

http://jsbin.com/oqugij/2/edit
### Icon

http://fortawesome.github.io/Font-Awesome/

``` css
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
```

``` css
<i class="fa-coffee"></i>
```

Sample: http://jsbin.com/EjOcekUJ/1/edit
### Students Level (Home Work)
1. Salman Sedighi @sedsalman [accSlider](http://jsbin.com/eSUWOWAx/1) :+1:
2. Alireza Akhlaghi @akhibing [V Menu](http://jsbin.com/IFiziGi/1/edit) :+1: 
3. Hamed Nosrati @hamednosrati [V Menu](http://jsbin.com/ILaBIzUd/4) :+1: 
4. Mohammad Amin Alizade Golestani  @MAgolestani [V Menu](http://jsbin.com/ADISUWE/2/edit) :+1: 
5. Alireza Haghpanah @alirezahp [V Menu](http://jsbin.com/ezituSi/2) :+1:  
6. Alireza Hassanzadeh Baradaran @alirezahb [ ](#)  :x: :facepunch:
7. Javad Pourhosaini @pourhosaini [ ](#) :punch: :no_entry: :no_entry_sign: :facepunch: :o: :red_circle: :facepunch::x:  :cake:
