### ISSUE TITLE
 C14 W3 S8

### ISSUE THREAD

**Issue by hbehkamal** [AliMD/1Tuts#644]
### Khafan ClassWork
1. register in firebase.com
2. get your unique url like me: https://shining-fire-1234.firebaseio.com/
3. check firebase.com/tutorial/
### Sample in our design pattern

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Ali.MD Tutorial</title>
  <meta name="description" content="An AliMD Web Technologies Tutorial" />
  <meta name="author" content="Ali Mihandoost" />
  <script src='https://cdn.firebase.com/v0/firebase.js'></script>
</head>
<body>
  <div class="container">
    <div id="chats"></div>
    <input id="esm" type="text" size="10" placeholder="Name" value="Ali.MD">
    <input id="msg" type="text" size="35" placeholder="Message">
  </div>
</body>
</html>
```

``` css
*{
  padding: 0;
  margin: 0;
}

body{
  background-color: #eee;
}

.container{
  width: 400px;
  margin: 40px auto 0;
}

#chats{
  width: 400px;
  height: 300px;
  border: 1px solid gray;
  background-color: #fff;
  overflow: auto;
}
```

**Note:** Replace yoururl

``` js
(function(){
  var
  chatDB = new Firebase("https://yoururl/chat"),
  msgKeyDown = function(evt){
    if(evt.keyCode === 13){
      chatDB.push({name: esm.value, text: msg.value});
      msg.value='';
    }
  },
  newchat = function(evt){
    var myval = evt.val();
    chats.innerHTML += '<b>'+myval.name+' : </b>'+myval.text+'<br/>';
  },
  setEvents = function(){
    msg.onkeydown = msgKeyDown;
    chatDB.on("child_added", newchat);
  },
  init = function(){
    setEvents();
  };

  init();
})();
```
