### ISSUE TITLE
C13 W2 S12

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#650]
## Modern CSS Page Layout

``` css
.row{
  *zoom:1;
  border: 1px dashed green;
}
.row:before,
.row:after{
  content:" ";
  display:table;
}
.row:after{
  clear:both;
}
.box{
  box-sizing: border-box;
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
}
```

http://jsbin.com/layoutdemo
### `box-sizing` Polyfill for iE 6,7

https://github.com/Schepp/box-sizing-polyfill
### Web page test

http://www.webpagetest.org
### HomeWork

https://github.com/1Tuts/C13-W2-Homework-Layout1
