### ISSUE TITLE
code highlight test

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#80]
baghiye zaban haram test kon.

``` ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```

``` php
<?php
$foo = "foo";
$bar = "bar";
echo "Foo is $foo", PHP_EOL;
echo "Bar is $bar";
// comments
?>
```

``` html
<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8" />
    <title>test</title>
</head>
<body>
    <div class="menu">
        <ul>
            <li><a href="page1.html">Page 1</a></li>
            <li><a href="page2.html">Page 2</a></li>
            <li><a href="page3.html">Page 3</a></li>
        </ul>
    </div>
</body>
</html>
```

``` css
*{
    padding: 0;
    margin: 0;
}

/* SlideShow
-------------------------------------------------- */

div.container{
    width       : 980px;
    margin      : 0 auto;
    padding-top : 1px;
}

div.slideshow{
    width      : 450px;
    height     : 324px;
    margin     : 30px auto 0;
    overflow   : hidden;
    position   : relative;
    background-image    : url('../images/loading.gif');
    background-repeat   : no-repeat;
    background-position : center center;
}
```

``` javascript
window.onload=function(){
    var slideshow = document.getElementsByClassName('slideshow').item(0);
    var lists = slideshow.getElementsByClassName('btns').item(0).getElementsByTagName('li');
    for (var i=0; i<lists.length; i++) {
        lists.item(i).onclick=function(){
            alert(i);
        }
    }
}
```
